### ISSUE TITLE
This newcomer to github has two big questions.

### ISSUE THREAD

**Issue by TerashiofSnagem** [gameboy9/FFRPSP#5]
1.) How do I download this randomnizer?

2.) Do I need any other programs to run the randomizer(Alternatively, how do I run the randomizer)?

**Comment by gameboy9** [comment]
1)  The releases page is a bit hard to find on the new versions of Github, I have to admit... https://github.com/gameboy9/FFRPSP/releases

2)  You probably will need to use the PPSSPP emulator with a FF1 PSP rom in order to use this program.
